"""Handing a conversation over to its successor.

Tasks 8.1-8.3 and 8.10 of 2026-08-07-conversation-handoff-rework.

A cutover is three things that must happen together or not at all: a successor exists, it has the
checkpoint, and the predecessor is closed. Doing the third without the second strands the work;
doing the second without the third leaves two open conversations both looking current.
"""

import subprocess

import pytest
from sqlalchemy import select

from hub.checkpoint_cutover import (
    CutoverRefusedError,
    cut_over,
    delivery_content,
    successor_title,
)
from hub.checkpoint_generation import CheckpointBody, render_body
from hub.checkpoint_trigger import consider
from hub.checkpoints import compute_envelope, create_checkpoint
from hub.db.engine import async_session_factory
from hub.db.models import (
    Agent,
    Checkpoint,
    Conversation,
    InboundQueueEntry,
    Project,
    Run,
    Runner,
)

from .test_checkpoint_generation import GOOD_BODY, _claude_stdout

PROJECT = "proj-test"
AGENT = "claude-1"


async def _conversation(db, conversation_id="conv-1", **overrides):
    fields = {
        "id": conversation_id,
        "project_id": PROJECT,
        "agent": AGENT,
        "lifecycle": "open",
        "origin": "operator",
        "title": "Wire up the worker",
    }
    fields.update(overrides)
    conversation = Conversation(**fields)
    db.add(conversation)
    await db.commit()
    return conversation


async def _ready_checkpoint(db, conversation):
    return await create_checkpoint(
        db,
        conversation,
        trigger="context_pressure",
        envelope=await compute_envelope(db, conversation),
        body=render_body(CheckpointBody(**GOOD_BODY), notes_incorporated=False),
    )


# --------------------------------------------------------------------------- titles


def test_a_successor_is_named_after_its_predecessor():
    """Derived so a chain reads as one line of work. Re-titling from the successor's first
    message would name it after an acknowledgement."""
    assert successor_title("Wire up the worker") == "Continued: Wire up the worker"


def test_a_chain_of_successors_does_not_stack_prefixes():
    assert successor_title("Continued: Wire up the worker") == "Continued: Wire up the worker"


def test_an_unnamed_predecessor_still_yields_a_usable_title():
    assert successor_title(None) == "Continued: Untitled conversation"
    assert successor_title("   ") == "Continued: Untitled conversation"


# --------------------------------------------------------------------------- the delivery


@pytest.mark.asyncio
async def test_the_successor_is_told_where_the_checkpoint_came_from(app):
    async with async_session_factory() as db:
        conversation = await _conversation(db)
        checkpoint = await _ready_checkpoint(db, conversation)
        content = delivery_content(checkpoint)

    # It must not read as the predecessor's own account of itself — that is the arrangement this
    # change replaces, and a successor that believes it is reading a peer's self-report will
    # trust it differently.
    assert "generated by the Hub from that conversation's record" in content
    assert "read from the database rather than recalled" in content
    assert "Start from \"Next actions\"" in content
    assert "Run pytest hub/tests/." in content


@pytest.mark.asyncio
async def test_cutover_creates_a_successor_delivers_and_archives(app):
    async with async_session_factory() as db:
        conversation = await _conversation(db, runtime_overrides={"permission_mode": "manual"})
        checkpoint = await _ready_checkpoint(db, conversation)

        successor, entry_id = await cut_over(db, conversation, checkpoint)

        entry = (
            await db.execute(select(InboundQueueEntry).where(InboundQueueEntry.id == entry_id))
        ).scalars().one()
        predecessor = await db.get(Conversation, "conv-1")

    assert successor.origin == "handoff"
    assert successor.title == "Continued: Wire up the worker"
    assert successor.lifecycle == "open"
    # The successor inherits what was in force. An inherited {"permission_mode": "manual"} is
    # what failed run-9058966b; dropping it at the boundary would change behaviour with nothing
    # on screen explaining why.
    assert successor.runtime_overrides == {"permission_mode": "manual"}

    # Conversation-scoped delivery, which `_render_hub_agent_context` cannot do — it writes one
    # file per agent, so three concurrent conversations would share one checkpoint.
    assert entry.conversation_id == successor.id
    assert entry.state == "queued"
    assert entry.origin_type == "checkpoint"
    assert entry.origin_agent is None

    assert predecessor.lifecycle == "archived"


@pytest.mark.asyncio
async def test_a_peer_binding_follows_the_line_of_work_across_a_cutover(app):
    """Correspondents keep reaching the same conversation. Without this, a cutover would scatter
    an exchange exactly the way recency routing used to."""
    async with async_session_factory() as db:
        conversation = await _conversation(
            db, bound_sender_conversation_id="conv-sender", bound_sender_agent=None
        )
        checkpoint = await _ready_checkpoint(db, conversation)
        successor, _ = await cut_over(db, conversation, checkpoint)

    assert successor.bound_sender_conversation_id == "conv-sender"


# --------------------------------------------------------------------------- refusals


@pytest.mark.asyncio
async def test_a_running_conversation_is_not_cut_over(app):
    """Archiving would have to stop a live run, which destroys work with no undo."""
    async with async_session_factory() as db:
        conversation = await _conversation(db)
        checkpoint = await _ready_checkpoint(db, conversation)
        db.add(
            Run(
                id="run-live",
                project_id=PROJECT,
                agent=AGENT,
                conversation_id="conv-1",
                status="running",
            )
        )
        await db.commit()

        with pytest.raises(CutoverRefusedError, match="run in progress"):
            await cut_over(db, conversation, checkpoint)

        predecessor = await db.get(Conversation, "conv-1")

    # Refused means untouched, not half-done.
    assert predecessor.lifecycle == "open"


@pytest.mark.asyncio
async def test_undelivered_work_blocks_a_cutover(app):
    """Archiving would strand it: nothing delivers into an archived conversation."""
    from hub.inbound_queue import new_entry

    async with async_session_factory() as db:
        conversation = await _conversation(db)
        checkpoint = await _ready_checkpoint(db, conversation)
        db.add(
            new_entry(
                project_id=PROJECT,
                agent=AGENT,
                origin_type="operator",
                content="one more thing",
                hop_depth=0,
                conversation_id="conv-1",
            )
        )
        await db.commit()

        with pytest.raises(CutoverRefusedError):
            await cut_over(db, conversation, checkpoint)


@pytest.mark.asyncio
async def test_an_unwritten_checkpoint_cannot_be_cut_over_to(app):
    """There would be nothing for the successor to continue from — which is the original defect
    wearing a new hat."""
    async with async_session_factory() as db:
        conversation = await _conversation(db)
        checkpoint = await create_checkpoint(
            db,
            conversation,
            trigger="run_failure",
            envelope=await compute_envelope(db, conversation),
            body=None,
        )
        with pytest.raises(CutoverRefusedError, match="unwritten"):
            await cut_over(db, conversation, checkpoint)

        predecessor = await db.get(Conversation, "conv-1")

    assert predecessor.lifecycle == "open"


# --------------------------------------------------------------------------- the trigger


async def _configured_project(db, **overrides):
    fields = {
        "checkpoint_mode": "automatic",
        "checkpoint_threshold_mode": "percent",
        "checkpoint_threshold_value": 80,
        "checkpoint_notes_value": 70,
        "checkpoint_runner_id": "runner-1",
        "checkpoint_model": "claude-haiku-4-5-20251001",
    }
    fields.update(overrides)
    project = await db.get(Project, PROJECT)
    if project is None:
        project = Project(id=PROJECT, name="Testbed")
        db.add(project)
    for key, value in fields.items():
        setattr(project, key, value)
    if await db.get(Runner, "runner-1") is None:
        db.add(
            Runner(
                id="runner-1",
                project_id=PROJECT,
                name="Cheap",
                cli="claude",
                model="claude-haiku-4-5-20251001",
            )
        )
    db.add(Agent(id="agent-1", project_id=PROJECT, name=AGENT))
    await db.commit()
    return project


@pytest.mark.asyncio
async def test_crossing_the_notes_point_asks_for_notes_and_takes_no_checkpoint(app, monkeypatch):
    def explode(*_a, **_k):  # pragma: no cover — the point is that nothing spawns
        raise AssertionError("no checkpoint should be generated at the notes point")

    async with async_session_factory() as db:
        await _configured_project(db)
        await _conversation(db)

    monkeypatch.setattr(subprocess, "run", explode)
    result = await consider(PROJECT, AGENT, "conv-1", context_tokens=None, percent=72.0)

    async with async_session_factory() as db:
        entries = (await db.execute(select(InboundQueueEntry))).scalars().all()

    assert result is None
    assert len(entries) == 1
    assert entries[0].origin_type == "checkpoint"
    assert "submit_checkpoint_notes" in entries[0].content
    # It must not read as an instruction to down tools.
    assert "This is not a request to stop." in entries[0].content


@pytest.mark.asyncio
async def test_notes_are_asked_for_once_not_on_every_reading(app, monkeypatch):
    async with async_session_factory() as db:
        await _configured_project(db)
        await _conversation(db)

    monkeypatch.setattr(subprocess, "run", lambda *_a, **_k: None)
    await consider(PROJECT, AGENT, "conv-1", context_tokens=None, percent=72.0)
    await consider(PROJECT, AGENT, "conv-1", context_tokens=None, percent=74.0)

    async with async_session_factory() as db:
        entries = (await db.execute(select(InboundQueueEntry))).scalars().all()

    assert len(entries) == 1


@pytest.mark.asyncio
async def test_crossing_the_threshold_under_automatic_generates_and_cuts_over(app, monkeypatch):
    def fake_run(cmd, **kwargs):
        stdout = _claude_stdout(
            GOOD_BODY
            if "checkpoint" in cmd[-1] or "objective" in cmd[-1]
            else {"files_changed": [], "task_ids": [], "unanswered_question_ids": []}
        )
        return subprocess.CompletedProcess(cmd, 0, stdout=stdout, stderr="")

    async with async_session_factory() as db:
        await _configured_project(db)
        await _conversation(db)

    monkeypatch.setattr("hub.worker.resolve_executable", lambda cmd: cmd)
    monkeypatch.setattr(subprocess, "run", fake_run)
    checkpoint_id = await consider(PROJECT, AGENT, "conv-1", context_tokens=None, percent=85.0)

    async with async_session_factory() as db:
        predecessor = await db.get(Conversation, "conv-1")
        successors = (
            (await db.execute(select(Conversation).where(Conversation.origin == "handoff")))
            .scalars()
            .all()
        )
        entries = (
            (
                await db.execute(
                    select(InboundQueueEntry).where(
                        InboundQueueEntry.origin_type == "checkpoint"
                    )
                )
            )
            .scalars()
            .all()
        )

    assert checkpoint_id is not None
    assert predecessor.lifecycle == "archived"
    assert len(successors) == 1
    assert len(entries) == 1
    assert entries[0].conversation_id == successors[0].id


@pytest.mark.asyncio
async def test_under_offered_nothing_is_made_and_nothing_is_cut_over(app, monkeypatch):
    """**This assertion inverted.** It used to read "a checkpoint is made but nothing is cut
    over", on the reasoning that generation no longer depends on the agent so there is nothing to
    ask permission for. That reasoning ignored the bill: generating billed a model call whether or
    not the operator wanted one, and at a low threshold billed it again every turn. `offered` now
    warns and spends nothing until asked."""

    def fake_run(cmd, **kwargs):
        return subprocess.CompletedProcess(cmd, 0, stdout=_claude_stdout(GOOD_BODY), stderr="")

    async with async_session_factory() as db:
        await _configured_project(db, checkpoint_mode="offered")
        await _conversation(db)

    def explode(*_a, **_k):  # pragma: no cover — `offered` warns; it does not spawn
        raise AssertionError("offered must not generate")

    monkeypatch.setattr(subprocess, "run", explode)
    checkpoint_id = await consider(PROJECT, AGENT, "conv-1", context_tokens=None, percent=85.0)

    async with async_session_factory() as db:
        predecessor = await db.get(Conversation, "conv-1")
        successors = (
            (await db.execute(select(Conversation).where(Conversation.origin == "handoff")))
            .scalars()
            .all()
        )

    assert checkpoint_id is None
    assert predecessor.lifecycle == "open"
    assert successors == []
    assert predecessor.checkpoint_warning == "due"


@pytest.mark.asyncio
async def test_an_off_project_does_nothing_at_any_reading(app, monkeypatch):
    def explode(*_a, **_k):  # pragma: no cover
        raise AssertionError("checkpointing is off")

    async with async_session_factory() as db:
        await _configured_project(db, checkpoint_mode="off")
        await _conversation(db)

    monkeypatch.setattr(subprocess, "run", explode)
    assert await consider(PROJECT, AGENT, "conv-1", context_tokens=None, percent=99.0) is None


@pytest.mark.asyncio
async def test_no_configured_runner_means_no_guessed_spawn(app, monkeypatch):
    """Spawning some other agent's expensive runner because none was configured is a bill the
    operator never agreed to."""

    def explode(*_a, **_k):  # pragma: no cover
        raise AssertionError("nothing should spawn without a configured runner")

    async with async_session_factory() as db:
        await _configured_project(db, checkpoint_runner_id=None)
        await _conversation(db)

    monkeypatch.setattr(subprocess, "run", explode)
    assert await consider(PROJECT, AGENT, "conv-1", context_tokens=None, percent=85.0) is None


@pytest.mark.asyncio
async def test_a_quiet_conversation_is_not_checkpointed_over_and_over(app, monkeypatch):
    """It sits above its threshold and every reading arrives while it does. Without a guard each
    one summarises nothing, at full price."""
    calls = []

    def fake_run(cmd, **kwargs):
        calls.append(cmd)
        return subprocess.CompletedProcess(cmd, 0, stdout=_claude_stdout(GOOD_BODY), stderr="")

    async with async_session_factory() as db:
        # `automatic`, because only that mode generates now — the guard being tested is about
        # not regenerating, which requires generating in the first place.
        await _configured_project(db, checkpoint_mode="automatic")
        await _conversation(db)
        db.add(
            Run(
                id="run-1",
                project_id=PROJECT,
                agent=AGENT,
                conversation_id="conv-1",
                status="completed",
            )
        )
        await db.commit()

    monkeypatch.setattr("hub.worker.resolve_executable", lambda cmd: cmd)
    monkeypatch.setattr(subprocess, "run", fake_run)
    first = await consider(PROJECT, AGENT, "conv-1", context_tokens=None, percent=85.0)
    second = await consider(PROJECT, AGENT, "conv-1", context_tokens=None, percent=86.0)

    assert first is not None
    assert second is None


# --------------------------------------------------------------------------- dispatch


@pytest.mark.asyncio
async def test_a_dispatched_consideration_is_held_until_it_finishes(app, monkeypatch):
    """`asyncio` keeps only a weak reference to a running task.

    `consider_from_reading` used to call `create_task` and drop the result, so the task could be
    collected before it ran — and because its `finally` never executed, the conversation stayed in
    `_in_flight` and could never fire again. Observed in production: readings crossed a 1,000-token
    threshold repeatedly, no worker was ever invoked, and nothing reported a problem.
    """
    import asyncio
    import gc

    from hub.checkpoint_trigger import _dispatched, _in_flight, consider_from_reading

    ran = asyncio.Event()

    async def fake_consider(*_args, **_kwargs):
        await asyncio.sleep(0.05)
        ran.set()

    monkeypatch.setattr("hub.checkpoint_trigger.consider", fake_consider)
    consider_from_reading(PROJECT, AGENT, "conv-dispatch", {"context_tokens": 50_000})

    # The reference the fix adds is what survives this.
    assert len(_dispatched) == 1
    gc.collect()

    await asyncio.wait_for(ran.wait(), timeout=2)
    await asyncio.sleep(0)

    assert ran.is_set()
    # And the guard clears, so the next reading is considered rather than silently skipped.
    assert "conv-dispatch" not in _in_flight


@pytest.mark.asyncio
async def test_a_reading_with_no_conversation_is_not_dispatched(app):
    """The guard that swallowed everything until `record_context_usage` learned to resolve one."""
    from hub.checkpoint_trigger import _dispatched, consider_from_reading

    before = len(_dispatched)
    consider_from_reading(PROJECT, AGENT, None, {"context_tokens": 50_000})
    assert len(_dispatched) == before


@pytest.mark.asyncio
async def test_a_real_reading_reaches_the_trigger(app, monkeypatch):
    """End to end from `record_context_usage`, which is the path production actually uses.

    Every other test here calls `consider` directly, and that is why three separate defects in the
    wiring between them all shipped undetected: the payload carried no conversation, the dispatched
    task was collected before it ran, and the conversation was read from the wrong dict. Each one
    silently dropped every reading while `consider` itself stayed perfectly correct.
    """
    import asyncio

    from hub.db.models import Conversation as Conv
    from hub.output_recording import record_context_usage

    seen = {}

    async def fake_consider(project_id, agent_name, conversation_id, **kwargs):
        seen.update(
            project_id=project_id, agent=agent_name, conversation_id=conversation_id, **kwargs
        )

    monkeypatch.setattr("hub.checkpoint_trigger.consider", fake_consider)

    async with async_session_factory() as db:
        db.add(
            Conv(
                id="conv-reading",
                project_id=PROJECT,
                agent=AGENT,
                lifecycle="open",
                provider_session_id="sess-reading",
            )
        )
        await db.commit()

        await record_context_usage(
            db,
            PROJECT,
            AGENT,
            {
                "status": "measured",
                "context_tokens": 50_000,
                "session_id": "sess-reading",
                "model": "claude-haiku-4-5-20251001",
                "source": "claude",
            },
        )
        # The dispatch is deliberately not awaited by its caller; let it run.
        await asyncio.sleep(0)
        await asyncio.sleep(0)

    assert seen.get("conversation_id") == "conv-reading"
    assert seen.get("context_tokens") == 50_000
    assert seen.get("agent") == AGENT


# --------------------------------------------------------------------------- warn before spending


@pytest.mark.asyncio
async def test_offered_warns_at_the_threshold_and_spends_nothing(app, monkeypatch):
    """Generating first billed a model call whether or not the operator wanted one — and at a low
    threshold billed it again every turn. The operator's framing: "if I want to extend a little
    longer I can"."""

    def explode(*_a, **_k):  # pragma: no cover — the point is that nothing spawns
        raise AssertionError("a warning must not generate a checkpoint")

    async with async_session_factory() as db:
        await _configured_project(db, checkpoint_mode="offered")
        await _conversation(db)

    monkeypatch.setattr(subprocess, "run", explode)
    result = await consider(PROJECT, AGENT, "conv-1", context_tokens=None, percent=85.0)

    async with async_session_factory() as db:
        conversation = await db.get(Conversation, "conv-1")
        checkpoints = (await db.execute(select(Checkpoint))).scalars().all()

    assert result is None
    assert conversation.checkpoint_warning == "due"
    assert checkpoints == []


@pytest.mark.asyncio
async def test_a_dismissed_warning_never_returns(app, monkeypatch):
    """Re-asking an operator who said "not yet" is the same as not letting them say it."""

    def explode(*_a, **_k):  # pragma: no cover
        raise AssertionError("a dismissed conversation must not checkpoint")

    async with async_session_factory() as db:
        await _configured_project(db, checkpoint_mode="offered")
        conversation = await _conversation(db)
        conversation.checkpoint_warning = "dismissed"
        await db.commit()

    monkeypatch.setattr(subprocess, "run", explode)
    assert await consider(PROJECT, AGENT, "conv-1", context_tokens=None, percent=99.0) is None

    async with async_session_factory() as db:
        conversation = await db.get(Conversation, "conv-1")

    # Still dismissed, not re-marked due.
    assert conversation.checkpoint_warning == "dismissed"


@pytest.mark.asyncio
async def test_automatic_still_acts_without_warning_first(app, monkeypatch):
    """Acting alone is what choosing `automatic` means; a warning there would be a mode that
    does not do what it says."""

    def fake_run(cmd, **kwargs):
        return subprocess.CompletedProcess(cmd, 0, stdout=_claude_stdout(GOOD_BODY), stderr="")

    async with async_session_factory() as db:
        await _configured_project(db, checkpoint_mode="automatic")
        await _conversation(db)

    monkeypatch.setattr("hub.worker.resolve_executable", lambda cmd: cmd)
    monkeypatch.setattr(subprocess, "run", fake_run)
    checkpoint_id = await consider(PROJECT, AGENT, "conv-1", context_tokens=None, percent=85.0)

    async with async_session_factory() as db:
        conversation = await db.get(Conversation, "conv-1")

    assert checkpoint_id is not None
    assert conversation.lifecycle == "archived"
    assert conversation.checkpoint_warning is None


@pytest.mark.asyncio
async def test_a_successor_is_warnable_again(app):
    """Dismissal is final for a conversation, not for a line of work."""
    async with async_session_factory() as db:
        conversation = await _conversation(db)
        conversation.checkpoint_warning = "dismissed"
        await db.commit()
        checkpoint = await _ready_checkpoint(db, conversation)
        successor, _ = await cut_over(db, conversation, checkpoint)

    assert successor.checkpoint_warning is None
