"""Project spec HTML storage and manifest-aware reconciliation endpoints.

Specs are HTML files generated by AW-Spec agents, synced to the Hub so the
UI can display them without filesystem access. ``project_specs`` is a
content cache — one row per (project, path), upserted on
``POST /project/specs/sync``. ``project_spec_snapshots`` is a per-source
reconciliation record — one row per (project, source_id) — that lets the
Hub compute drift (unfiled/missing/stale/conflicting documents) across
possibly multiple machines syncing the same project, and lets it detect
deletions without ever letting one stale checkout delete another's content.

The Hub is the security boundary here: it re-validates every path and
re-parses every manifest itself (``hub.spec_manifest``) rather than
trusting the client's classification.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Set, Tuple

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, field_validator
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ...auth import get_project
from ...db.engine import get_session
from ...db.models import ProjectSpec, ProjectSpecSnapshot
from ...spec_manifest import (
    MANIFEST_MAX_BYTES,
    Manifest,
    ManifestDiagnostic,
    SpecPathError,
    compute_intrinsic_conflicts,
    load_manifest,
    validate_spec_path,
)
from ...sse import sse_manager

router = APIRouter(prefix="/project", tags=["spec"])

MAX_CONTENT_BYTES = 2 * 1024 * 1024  # ~2MB
MAX_INVENTORY_ENTRIES = 1000
# Comfortably above normal watchdog polling and the 120s heartbeat stale
# threshold (see hub/hub/api/v1/agent_trigger.py) — a source that hasn't
# reconciled in this window is no longer trusted to claim a path.
ACTIVE_SOURCE_TTL_SECONDS = 300

MANIFEST_STATES = {"valid", "absent", "unreadable", "invalid"}


class SpecSyncRequest(BaseModel):
    path: str
    content: str

    @field_validator("path")
    @classmethod
    def _validate_path(cls, v: str) -> str:
        try:
            return validate_spec_path(v)
        except SpecPathError as exc:
            raise ValueError(str(exc)) from exc


class SpecReconcileRequest(BaseModel):
    source_id: str
    manifest_text: Optional[str] = None
    manifest_state: str
    discovered_paths: List[str]
    prune: bool = False

    @field_validator("source_id")
    @classmethod
    def _validate_source_id(cls, v: str) -> str:
        if not v or len(v) > 64:
            raise ValueError("source_id must be a non-empty string up to 64 characters")
        return v

    @field_validator("manifest_state")
    @classmethod
    def _validate_manifest_state(cls, v: str) -> str:
        if v not in MANIFEST_STATES:
            raise ValueError(f"manifest_state must be one of {sorted(MANIFEST_STATES)}")
        return v

    @field_validator("discovered_paths")
    @classmethod
    def _validate_discovered_paths(cls, v: List[str]) -> List[str]:
        if len(v) > MAX_INVENTORY_ENTRIES:
            raise ValueError(f"discovered_paths exceeds {MAX_INVENTORY_ENTRIES} entries")
        safe = []
        for path in v:
            try:
                safe.append(validate_spec_path(path))
            except SpecPathError as exc:
                raise ValueError(f"unsafe discovered path {path!r}: {exc}") from exc
        return safe


@router.post("/specs/sync")
async def sync_spec(
    body: SpecSyncRequest,
    project: Tuple[str, str] = Depends(get_project),
    session: AsyncSession = Depends(get_session),
):
    """Upsert a spec HTML file for this project and broadcast ``spec_updated``."""
    project_id, _ = project

    if len(body.content.encode("utf-8")) > MAX_CONTENT_BYTES:
        raise HTTPException(status_code=413, detail="spec content exceeds 2MB limit")

    result = await session.execute(
        select(ProjectSpec).where(
            ProjectSpec.project_id == project_id, ProjectSpec.path == body.path
        )
    )
    row = result.scalars().first()
    if row:
        row.content = body.content
    else:
        row = ProjectSpec(project_id=project_id, path=body.path, content=body.content)
        session.add(row)

    await session.commit()
    await session.refresh(row)

    await sse_manager.broadcast(project_id, "spec_updated", {"path": body.path})

    return {"path": row.path, "updated_at": row.updated_at.isoformat()}


@router.get("/specs")
async def list_specs(
    project: Tuple[str, str] = Depends(get_project),
    session: AsyncSession = Depends(get_session),
):
    """List all specs for this project, enriched with manifest state and drift.

    Additive over the legacy shape: every entry still has ``path`` and
    ``updated_at``. New: ``home``, ``manifest``, ``missing``, ``diagnostics``,
    and per-entry ``title``/``kind``/``status``/``parent``/``order``/``state``
    when a document is covered by a valid manifest.
    """
    project_id, _ = project
    state = await _compute_state(session, project_id)
    return {
        "specs": state.specs,
        "home": state.home,
        "manifest": state.manifest_summary,
        "missing": state.missing,
        "diagnostics": state.diagnostics,
    }


@router.get("/spec")
async def get_spec(
    path: str = Query(...),
    project: Tuple[str, str] = Depends(get_project),
    session: AsyncSession = Depends(get_session),
):
    """Return one spec's full content; 404 if the path is unknown."""
    project_id, _ = project
    result = await session.execute(
        select(ProjectSpec).where(ProjectSpec.project_id == project_id, ProjectSpec.path == path)
    )
    row = result.scalars().first()
    if not row:
        raise HTTPException(status_code=404, detail="spec not found")
    return {"path": row.path, "content": row.content, "updated_at": row.updated_at.isoformat()}


@router.post("/specs/reconcile")
async def reconcile_specs(
    body: SpecReconcileRequest,
    project: Tuple[str, str] = Depends(get_project),
    session: AsyncSession = Depends(get_session),
):
    """Upsert this source's snapshot, optionally prune true orphans, and
    return the recomputed drift/diagnostics.

    Never deletes stored content unless ``prune=true`` — and even then, only
    rows no active source (inventory or valid manifest) claims. The Hub
    re-validates ``manifest_text`` itself rather than trusting
    ``manifest_state`` from the client.
    """
    project_id, _ = project

    if (
        body.manifest_text is not None
        and len(body.manifest_text.encode("utf-8")) > MANIFEST_MAX_BYTES
    ):
        raise HTTPException(status_code=413, detail="manifest exceeds size limit")

    stored_state = body.manifest_state
    stored_diagnostics: List[Dict[str, Any]] = []
    if body.manifest_text is not None:
        manifest, diags = load_manifest(body.manifest_text)
        stored_state = "valid" if manifest is not None else "invalid"
        stored_diagnostics = [d.to_dict() for d in diags]

    result = await session.execute(
        select(ProjectSpecSnapshot).where(
            ProjectSpecSnapshot.project_id == project_id,
            ProjectSpecSnapshot.source_id == body.source_id,
        )
    )
    row = result.scalars().first()
    if row:
        row.manifest_content = body.manifest_text
        row.manifest_state = stored_state
        row.inventory = body.discovered_paths
        row.diagnostics = stored_diagnostics
    else:
        row = ProjectSpecSnapshot(
            project_id=project_id,
            source_id=body.source_id,
            manifest_content=body.manifest_text,
            manifest_state=stored_state,
            inventory=body.discovered_paths,
            diagnostics=stored_diagnostics,
        )
        session.add(row)
    await session.commit()

    pruned: List[str] = []
    if body.prune:
        pre_state = await _compute_state(session, project_id)
        content_result = await session.execute(
            select(ProjectSpec).where(ProjectSpec.project_id == project_id)
        )
        for content_row in content_result.scalars().all():
            if content_row.path not in pre_state.claimed:
                pruned.append(content_row.path)
                await session.delete(content_row)
        if pruned:
            await session.commit()

    state = await _compute_state(session, project_id)
    reason = "prune" if pruned else ("manifest" if body.manifest_text is not None else "inventory")
    await sse_manager.broadcast(project_id, "spec_updated", {"reason": reason})

    return {
        "home": state.home,
        "manifest": state.manifest_summary,
        "missing": state.missing,
        "diagnostics": state.diagnostics,
        "pruned": sorted(pruned),
    }


# ---------------------------------------------------------------------------
# Drift computation — shared by GET /specs and POST /specs/reconcile
# ---------------------------------------------------------------------------


@dataclass
class _SnapshotView:
    source_id: str
    manifest_content: Optional[str]
    manifest_state: str  # Hub-recomputed, not necessarily what the client sent
    manifest: Optional[Manifest]
    manifest_diagnostics: List[ManifestDiagnostic]
    inventory: List[str]
    updated_at: datetime


@dataclass
class _DriftState:
    specs: List[Dict[str, Any]]
    home: Optional[str]
    manifest_summary: Optional[Dict[str, Any]]
    missing: List[Dict[str, Any]]
    diagnostics: List[Dict[str, Any]]
    claimed: Set[str]


def _age_seconds(updated_at: datetime, now: datetime) -> float:
    a = updated_at.replace(tzinfo=None) if updated_at.tzinfo else updated_at
    b = now.replace(tzinfo=None) if now.tzinfo else now
    return (b - a).total_seconds()


def _snapshot_view(row: ProjectSpecSnapshot) -> _SnapshotView:
    manifest: Optional[Manifest] = None
    diagnostics: List[ManifestDiagnostic] = []
    state = row.manifest_state
    if row.manifest_content is not None:
        manifest, diagnostics = load_manifest(row.manifest_content)
        state = "valid" if manifest is not None else "invalid"
    return _SnapshotView(
        source_id=row.source_id,
        manifest_content=row.manifest_content,
        manifest_state=state,
        manifest=manifest,
        manifest_diagnostics=diagnostics,
        inventory=list(row.inventory or []),
        # Normalized to naive UTC: SQLite round-trips DateTime(timezone=True)
        # as naive, while a freshly-flushed row's default (_now()) is aware —
        # comparing the two directly raises TypeError.
        updated_at=row.updated_at.replace(tzinfo=None) if row.updated_at.tzinfo else row.updated_at,
    )


def _manifest_shape(manifest: Optional[Manifest]) -> Any:
    if manifest is None:
        return None
    return (
        manifest.home,
        tuple(sorted((d.path, d.parent, d.order, d.kind, d.status) for d in manifest.documents)),
    )


def _diag(code: str, **kwargs: Any) -> Dict[str, Any]:
    base: Dict[str, Any] = {
        "code": code,
        "path": None,
        "field": None,
        "expected": None,
        "actual": None,
        "source_ids": None,
    }
    base.update(kwargs)
    return base


def _select_home(
    primary: Optional[_SnapshotView], content_rows: Dict[str, ProjectSpec]
) -> Optional[str]:
    if primary is not None and primary.manifest is not None:
        if primary.manifest.home in content_rows:
            return primary.manifest.home
        for preferred_kind in ("baseline", "system-map"):
            candidates = sorted(
                (
                    d
                    for d in primary.manifest.documents
                    if d.kind == preferred_kind and d.path in content_rows
                ),
                key=lambda d: (d.order, d.path),
            )
            if candidates:
                return candidates[0].path
        candidates = sorted(
            (d for d in primary.manifest.documents if d.path in content_rows),
            key=lambda d: (d.order, d.path),
        )
        if candidates:
            return candidates[0].path
    # No valid manifest (or none of its documents are available) — legacy fallback.
    if not content_rows:
        return None
    if "spec/spec.html" in content_rows:
        return "spec/spec.html"
    return sorted(content_rows.keys())[0]


async def _compute_state(session: AsyncSession, project_id: str) -> _DriftState:
    now = datetime.now(timezone.utc)

    snapshot_result = await session.execute(
        select(ProjectSpecSnapshot).where(ProjectSpecSnapshot.project_id == project_id)
    )
    views = [_snapshot_view(r) for r in snapshot_result.scalars().all()]
    active = [v for v in views if _age_seconds(v.updated_at, now) < ACTIVE_SOURCE_TTL_SECONDS]

    content_result = await session.execute(
        select(ProjectSpec).where(ProjectSpec.project_id == project_id)
    )
    content_rows: Dict[str, ProjectSpec] = {r.path: r for r in content_result.scalars().all()}

    diagnostics: List[Dict[str, Any]] = []

    claimed: Set[str] = set()
    for v in active:
        claimed.update(v.inventory)
        if v.manifest is not None:
            claimed.update(doc.path for doc in v.manifest.documents)

    for v in active:
        if v.manifest_content is not None and v.manifest is None:
            for d in v.manifest_diagnostics:
                diag = d.to_dict()
                diag["source_ids"] = [v.source_id]
                diagnostics.append(diag)

    active_valid = [v for v in active if v.manifest is not None]
    primary = max(active_valid, key=lambda v: v.updated_at) if active_valid else None

    if primary is not None:
        primary_shape = _manifest_shape(primary.manifest)
        for v in active_valid:
            if v is primary or _manifest_shape(v.manifest) == primary_shape:
                continue
            diagnostics.append(
                _diag("active_source_conflict", source_ids=[primary.source_id, v.source_id])
            )

    by_path = primary.manifest.by_path() if primary is not None and primary.manifest else {}
    has_active_source = bool(active)

    specs: List[Dict[str, Any]] = []
    for path, row in content_rows.items():
        doc = by_path.get(path)
        entry: Dict[str, Any] = {"path": path, "updated_at": row.updated_at.isoformat()}
        if doc is not None:
            # A document the current authoritative manifest lists is never
            # stale — its path is already in `claimed` by construction.
            entry.update(
                title=doc.title,
                kind=doc.kind,
                status=doc.status,
                parent=doc.parent,
                order=doc.order,
                state="filed",
            )
        elif not has_active_source:
            # No reconciliation has ever happened for this project (a legacy
            # CLI that only calls /specs/sync) — available, not drift.
            entry["state"] = "unindexed"
        elif path in claimed:
            entry["state"] = "unfiled"
            diagnostics.append(_diag("unfiled_document", path=path))
        else:
            entry["state"] = "stale"
            diagnostics.append(_diag("stale_row", path=path))
        specs.append(entry)

    missing: List[Dict[str, Any]] = []
    if primary is not None and primary.manifest is not None:
        for doc in primary.manifest.documents:
            if doc.path not in content_rows:
                missing.append(
                    {
                        "path": doc.path,
                        "title": doc.title,
                        "kind": doc.kind,
                        "status": doc.status,
                        "parent": doc.parent,
                        "order": doc.order,
                    }
                )
                diagnostics.append(_diag("missing_document", path=doc.path))

        content_by_path = {p: r.content for p, r in content_rows.items()}
        for d in compute_intrinsic_conflicts(primary.manifest, content_by_path):
            diag = d.to_dict()
            diag["source_ids"] = [primary.source_id]
            diagnostics.append(diag)

    def _sort_key(entry: Dict[str, Any]) -> Tuple[int, Any, str]:
        if entry.get("state") == "filed":
            return (0, entry["order"], entry["path"])
        return (1, entry["path"] != "spec/spec.html", entry["path"])

    specs.sort(key=_sort_key)

    manifest_summary: Optional[Dict[str, Any]] = None
    if primary is not None and primary.manifest is not None:
        manifest_summary = {
            "state": "valid",
            "version": primary.manifest.version,
            "source_id": primary.source_id,
            "updated_at": primary.updated_at.isoformat(),
        }
    elif active:
        newest = max(active, key=lambda v: v.updated_at)
        manifest_summary = {
            "state": newest.manifest_state,
            "version": None,
            "source_id": newest.source_id,
            "updated_at": newest.updated_at.isoformat(),
        }

    return _DriftState(
        specs=specs,
        home=_select_home(primary, content_rows),
        manifest_summary=manifest_summary,
        missing=missing,
        diagnostics=diagnostics,
        claimed=claimed,
    )
