"""Project spec HTML storage endpoints.

Specs are HTML files generated by the CLI (e.g. OpenSpec renders) synced to
the Hub so the UI can display them without filesystem access. One row per
(project, path); synced content upserts and broadcasts a ``spec_updated``
SSE event so the UI refreshes.
"""

import re
from typing import Tuple

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, field_validator
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ...auth import get_project
from ...db.engine import get_session
from ...db.models import ProjectSpec
from ...sse import sse_manager

router = APIRouter(prefix="/project", tags=["spec"])

SPEC_PATH_RE = re.compile(r"^spec/(changes/[a-z0-9][a-z0-9-]*/)?spec\.html$")
MAX_CONTENT_BYTES = 2 * 1024 * 1024  # ~2MB


class SpecSyncRequest(BaseModel):
    path: str
    content: str

    @field_validator("path")
    @classmethod
    def _validate_path(cls, v: str) -> str:
        if not SPEC_PATH_RE.match(v):
            raise ValueError(
                "path must be 'spec/spec.html' or 'spec/changes/<slug>/spec.html'"
            )
        return v


@router.post("/specs/sync")
async def sync_spec(
    body: SpecSyncRequest,
    project: Tuple[str, str] = Depends(get_project),
    session: AsyncSession = Depends(get_session),
):
    """Upsert a spec HTML file for this project and broadcast ``spec_updated``."""
    project_id, _ = project

    if len(body.content.encode("utf-8")) > MAX_CONTENT_BYTES:
        raise HTTPException(status_code=413, detail="spec content exceeds 2MB limit")

    result = await session.execute(
        select(ProjectSpec).where(
            ProjectSpec.project_id == project_id, ProjectSpec.path == body.path
        )
    )
    row = result.scalars().first()
    if row:
        row.content = body.content
    else:
        row = ProjectSpec(project_id=project_id, path=body.path, content=body.content)
        session.add(row)

    await session.commit()
    await session.refresh(row)

    await sse_manager.broadcast(project_id, "spec_updated", {"path": body.path})

    return {"path": row.path, "updated_at": row.updated_at.isoformat()}


@router.get("/specs")
async def list_specs(
    project: Tuple[str, str] = Depends(get_project),
    session: AsyncSession = Depends(get_session),
):
    """List all specs for this project — ``spec/spec.html`` first, then by path."""
    project_id, _ = project
    result = await session.execute(
        select(ProjectSpec).where(ProjectSpec.project_id == project_id)
    )
    rows = sorted(
        result.scalars().all(),
        key=lambda r: (r.path != "spec/spec.html", r.path),
    )
    return {"specs": [{"path": r.path, "updated_at": r.updated_at.isoformat()} for r in rows]}


@router.get("/spec")
async def get_spec(
    path: str = Query(...),
    project: Tuple[str, str] = Depends(get_project),
    session: AsyncSession = Depends(get_session),
):
    """Return one spec's full content; 404 if the path is unknown."""
    project_id, _ = project
    result = await session.execute(
        select(ProjectSpec).where(
            ProjectSpec.project_id == project_id, ProjectSpec.path == path
        )
    )
    row = result.scalars().first()
    if not row:
        raise HTTPException(status_code=404, detail="spec not found")
    return {"path": row.path, "content": row.content, "updated_at": row.updated_at.isoformat()}
