"""Handing a conversation over to its successor.

A cutover is three things that must happen together or not at all: a successor conversation
exists, it has been given the checkpoint, and the predecessor is closed. Doing the third without
the second strands the work; doing the second without the third leaves two open conversations
both looking current.

The checkpoint reaches the successor as an **`InboundQueueEntry`**, not through
`_render_hub_agent_context`. That path writes one context file per *agent*, so it physically
cannot carry a per-conversation payload — an agent running three conversations would get one
file, and the last checkpoint written would be the one all three read.
"""

from __future__ import annotations

import logging
from typing import Optional, Tuple

from .checkpoint_generation import render_checkpoint
from .conversations import CONVERSATION_TITLE_MAX_LENGTH, archivable, archive, new_conversation
from .db.models import Checkpoint, Conversation
from .inbound_queue import new_entry

logger = logging.getLogger(__name__)

_SUCCESSOR_PREFIX = "Continued: "

_DELIVERY_PREAMBLE = """\
This conversation continues earlier work. The checkpoint below was generated by the Hub from that \
conversation's record; it is not something the previous agent wrote about itself, and the files, \
tasks, questions and overrides it lists were read from the database rather than recalled.

Start from "Next actions". If something you need is missing, say so rather than guessing — the \
predecessor conversation still exists and can be consulted.

"""


class CutoverRefusedError(RuntimeError):
    """The predecessor cannot be closed, so the handover must not proceed."""


def successor_title(previous: Optional[str]) -> str:
    """A successor's title, derived from its predecessor's rather than regenerated.

    Derived so a chain reads as one line of work in the navigation tree. Re-titling from the new
    conversation's first message would name it after whatever the successor happened to say
    first, which is usually an acknowledgement.
    """
    # Stripped *before* the fallback: a title of only whitespace is as unnamed as no title, and
    # falling back afterwards would produce the bare prefix "Continued: ".
    base = (previous or "").strip() or "Untitled conversation"
    # A chain of successors must not stack prefixes into "Continued: Continued: …".
    candidate = base if base.startswith(_SUCCESSOR_PREFIX) else f"{_SUCCESSOR_PREFIX}{base}"
    return candidate[:CONVERSATION_TITLE_MAX_LENGTH]


def delivery_content(checkpoint: Checkpoint) -> str:
    """What the successor actually receives: the rendered checkpoint, framed."""
    return _DELIVERY_PREAMBLE + render_checkpoint(checkpoint)


async def cut_over(
    db,
    predecessor: Conversation,
    checkpoint: Checkpoint,
    *,
    hop_depth: int = 0,
    auto_continue: bool = False,
) -> Tuple[Conversation, str]:
    """Open a successor, give it the checkpoint, and archive the predecessor.

    Refuses outright when the predecessor cannot be archived — a run still in progress, or
    undelivered queue entries that archiving would strand. Cutting over anyway would leave the
    operator with a successor holding a summary and a predecessor holding the actual work.

    Order matters: the successor and its entry are created **before** the predecessor is
    archived, so a failure part-way leaves the predecessor open and usable rather than closed
    with nowhere to continue.
    """
    if checkpoint.status != "ready":
        raise CutoverRefusedError(
            f"Checkpoint {checkpoint.id} is {checkpoint.status!r}; only a ready checkpoint "
            "carries something to continue from."
        )

    refusal = await archivable(db, predecessor)
    if refusal is not None:
        raise CutoverRefusedError(refusal)

    successor = new_conversation(
        project_id=predecessor.project_id,
        agent=predecessor.agent,
        origin="handoff",
    )
    successor.title = successor_title(predecessor.title)
    # Derived, not typed by anyone — but an operator renaming it must not then be overwritten by
    # the titler, which is what this flag governs.
    successor.title_set_by_operator = True
    # The successor inherits what was in force. An inherited {"permission_mode": "manual"} is
    # what failed run-9058966b; dropping the overrides at the boundary would make a conversation
    # behave differently from its predecessor for reasons nothing on screen explains.
    successor.runtime_overrides = (
        dict(predecessor.runtime_overrides) if predecessor.runtime_overrides else None
    )
    # A peer binding follows the line of work, not the thread id, so correspondents keep
    # reaching the same conversation across a cutover.
    successor.bound_sender_conversation_id = predecessor.bound_sender_conversation_id
    successor.bound_sender_agent = predecessor.bound_sender_agent
    db.add(successor)

    entry = new_entry(
        project_id=predecessor.project_id,
        agent=predecessor.agent,
        origin_type="checkpoint",
        content=delivery_content(checkpoint),
        hop_depth=hop_depth,
        conversation_id=successor.id,
        session_mode="new",
    )
    db.add(entry)

    archive(predecessor)
    await db.commit()

    logger.info(
        "cut %s over to %s on checkpoint %s", predecessor.id, successor.id, checkpoint.id
    )

    if auto_continue:
        # Started here rather than left for the operator to trigger with a message. The successor
        # already holds everything it needs; requiring someone to invent a sentence to get it
        # moving made the handover a dead end. Imported locally — the scheduler reaches back into
        # the trigger path that calls this.
        from .turn_scheduler import schedule_agent

        result = await schedule_agent(predecessor.project_id, predecessor.agent)
        if result.waiting_reason:
            # Not an error: the queue entry is durable, so the work is not lost — it simply has
            # not started yet, and the operator can start it themselves.
            logger.info(
                "successor %s did not start immediately: %s", successor.id, result.waiting_reason
            )

    return successor, entry.id
