"""Handing a conversation over to its successor.

A cutover is three things that must happen together or not at all: a successor conversation
exists, it has been given the checkpoint, and the predecessor is closed. Doing the third without
the second strands the work; doing the second without the third leaves two open conversations
both looking current.

The checkpoint reaches the successor as an **`InboundQueueEntry`**, not through
`_render_hub_agent_context`. That path writes one context file per *agent*, so it physically
cannot carry a per-conversation payload — an agent running three conversations would get one
file, and the last checkpoint written would be the one all three read.
"""

from __future__ import annotations

import logging
from typing import Optional, Tuple

from sqlalchemy import select, update
from sqlalchemy.exc import IntegrityError

from .checkpoint_generation import render_checkpoint
from .conversations import CONVERSATION_TITLE_MAX_LENGTH, archivable, archive, new_conversation
from .db.models import Checkpoint, Conversation
from .inbound_queue import new_entry

logger = logging.getLogger(__name__)

_SUCCESSOR_PREFIX = "Continued: "

_DELIVERY_PREAMBLE = """\
This conversation continues earlier work. The checkpoint below was generated by the Hub from that \
conversation's record; it is not something the previous agent wrote about itself, and the files, \
tasks, questions and overrides it lists were read from the database rather than recalled.

Start from "Next actions". If something you need is missing, say so rather than guessing — the \
predecessor conversation still exists and can be consulted.

"""


class CutoverRefusedError(RuntimeError):
    """The predecessor cannot be closed, so the handover must not proceed."""


def successor_title(previous: Optional[str]) -> str:
    """A successor's title, derived from its predecessor's rather than regenerated.

    Derived so a chain reads as one line of work in the navigation tree. Re-titling from the new
    conversation's first message would name it after whatever the successor happened to say
    first, which is usually an acknowledgement.
    """
    # Stripped *before* the fallback: a title of only whitespace is as unnamed as no title, and
    # falling back afterwards would produce the bare prefix "Continued: ".
    base = (previous or "").strip() or "Untitled conversation"
    # A chain of successors must not stack prefixes into "Continued: Continued: …".
    candidate = base if base.startswith(_SUCCESSOR_PREFIX) else f"{_SUCCESSOR_PREFIX}{base}"
    return candidate[:CONVERSATION_TITLE_MAX_LENGTH]


async def _handover_of(db, conversation_id: str) -> Optional[Tuple[str, str]]:
    """`(checkpoint id, successor id)` of the checkpoint that handed this conversation over."""
    row = (
        await db.execute(
            select(Checkpoint.id, Checkpoint.cut_over_to_conversation_id).where(
                Checkpoint.conversation_id == conversation_id,
                Checkpoint.cut_over_to_conversation_id.is_not(None),
            )
        )
    ).first()
    return None if row is None else (row[0], row[1])


def _already_handed_over(
    conversation_id: str, checkpoint_id: str, prior: Tuple[str, str]
) -> CutoverRefusedError:
    handed_by, successor = prior
    if handed_by == checkpoint_id:
        return CutoverRefusedError(
            f"Checkpoint {checkpoint_id} was already cut over to {successor}; that conversation "
            "holds the work."
        )
    return CutoverRefusedError(
        f"Conversation {conversation_id} was already handed over to {successor} (checkpoint "
        f"{handed_by}); continue there, or keep working in this one."
    )


async def _lost_the_race(
    db, predecessor_id: str, checkpoint_id: str, error: Optional[IntegrityError]
) -> Exception:
    """The refusal for a press that lost to a concurrent one, read after the rollback.

    An `IntegrityError` that names no handed-over checkpoint came from some other constraint, and
    is returned as itself rather than dressed as a refusal that names nothing.
    """
    prior = await _handover_of(db, predecessor_id)
    if prior is None:
        return (
            error
            if error is not None
            else RuntimeError(
                f"cutover claim on checkpoint {checkpoint_id} matched no row and none is recorded"
            )
        )
    return _already_handed_over(predecessor_id, checkpoint_id, prior)


def delivery_content(checkpoint: Checkpoint) -> str:
    """What the successor actually receives: the rendered checkpoint, framed."""
    return _DELIVERY_PREAMBLE + render_checkpoint(checkpoint)


async def cut_over(
    db,
    predecessor: Conversation,
    checkpoint: Checkpoint,
    *,
    hop_depth: int = 0,
    auto_continue: bool = False,
) -> Tuple[Conversation, str]:
    """Open a successor, give it the checkpoint, and archive the predecessor.

    Refuses outright when the predecessor cannot be archived — a run still in progress, or
    undelivered queue entries that archiving would strand. Cutting over anyway would leave the
    operator with a successor holding a summary and a predecessor holding the actual work. Also
    refuses a conversation that was already handed over, and a checkpoint that was already cut
    over. That is recorded on the checkpoint (`cut_over_to_conversation_id`), not inferred from the
    predecessor being archived: reopening a handed-over conversation clears its archived state and
    used to re-arm the checkpoint (F293). The claim is a conditional UPDATE, and a partial unique
    index on `checkpoints.conversation_id` backs it for two different checkpoints of one
    conversation, so two simultaneous presses cannot both win (F294).

    Order matters: the successor and its entry are created **before** the predecessor is
    archived, so a failure part-way leaves the predecessor open and usable rather than closed
    with nowhere to continue.
    """
    # Plain strings before any write: a rollback expires every instance in the session, and
    # reading one afterwards raises MissingGreenlet, which a route answers as a 500.
    checkpoint_id = checkpoint.id
    predecessor_id = predecessor.id
    if checkpoint.status != "ready":
        raise CutoverRefusedError(
            f"Checkpoint {checkpoint.id} is {checkpoint.status!r}; only a ready checkpoint "
            "carries something to continue from."
        )

    # The handover record comes first, so "unarchive it first" is said only to a conversation that
    # was never handed over, where following it is correct (design D4).
    prior = await _handover_of(db, predecessor.id)
    if prior is not None:
        raise _already_handed_over(predecessor.id, checkpoint.id, prior)

    # Asked here rather than left to `archivable`, whose first line returns None for an archived
    # conversation. That early return is right for what `archivable` is for -- archiving an
    # archived conversation is a no-op, not an error -- and wrong as the question a cutover asks.
    # A conversation the operator archived by hand reaches here; refusing is honest, since a
    # cutover closes a conversation and this one is closed.
    if predecessor.lifecycle == "archived":
        raise CutoverRefusedError(
            f"Conversation {predecessor.id} is already archived, so there is nothing left to "
            "hand over. A cutover closes a conversation and opens its successor; unarchive it "
            "first."
        )

    refusal = await archivable(db, predecessor)
    if refusal is not None:
        raise CutoverRefusedError(refusal)

    successor = new_conversation(
        project_id=predecessor.project_id,
        agent=predecessor.agent,
        origin="handoff",
    )
    successor.title = successor_title(predecessor.title)
    # Derived, not typed by anyone — but an operator renaming it must not then be overwritten by
    # the titler, which is what this flag governs.
    successor.title_set_by_operator = True
    # The successor inherits what was in force. An inherited {"permission_mode": "manual"} is
    # what failed run-9058966b; dropping the overrides at the boundary would make a conversation
    # behave differently from its predecessor for reasons nothing on screen explains.
    successor.runtime_overrides = (
        dict(predecessor.runtime_overrides) if predecessor.runtime_overrides else None
    )
    # A peer binding follows the line of work, not the thread id, so correspondents keep
    # reaching the same conversation across a cutover.
    successor.bound_sender_conversation_id = predecessor.bound_sender_conversation_id
    successor.bound_sender_agent = predecessor.bound_sender_agent
    # Same line of work under a new id -- sending FROM the successor must still reach a
    # thread bound to any conversation in this lineage, not just to the predecessor's id.
    successor.lineage_id = predecessor.lineage_id
    db.add(successor)

    entry = new_entry(
        project_id=predecessor.project_id,
        agent=predecessor.agent,
        origin_type="checkpoint",
        content=delivery_content(checkpoint),
        hop_depth=hop_depth,
        conversation_id=successor.id,
        session_mode="new",
    )
    db.add(entry)

    archive(predecessor)

    # Both callers arrive with nothing pending, so rolling back below discards only this
    # function's own adds. A caller that staged changes before `cut_over` would lose them, and its
    # instances come back expired either way: read plain ids, never `checkpoint.id`, afterwards.
    successor_id = successor.id
    entry_id = entry.id
    await db.flush()
    try:
        claim = await db.execute(
            update(Checkpoint)
            .where(
                Checkpoint.id == checkpoint_id,
                Checkpoint.cut_over_to_conversation_id.is_(None),
            )
            .values(cut_over_to_conversation_id=successor_id)
            .execution_options(synchronize_session=False)
        )
        claimed = claim.rowcount == 1
        if claimed:
            await db.commit()
    except IntegrityError as error:
        await db.rollback()
        raise await _lost_the_race(db, predecessor_id, checkpoint_id, error) from error
    if not claimed:
        await db.rollback()
        raise await _lost_the_race(db, predecessor_id, checkpoint_id, None)

    logger.info("cut %s over to %s on checkpoint %s", predecessor_id, successor_id, checkpoint_id)

    if auto_continue:
        # Started here rather than left for the operator to trigger with a message. The successor
        # already holds everything it needs; requiring someone to invent a sentence to get it
        # moving made the handover a dead end. Imported locally — the scheduler reaches back into
        # the trigger path that calls this.
        from .turn_scheduler import schedule_agent

        result = await schedule_agent(predecessor.project_id, predecessor.agent)
        # The third conversation-addressed use of `schedule_agent`, and it obeys the same rule as
        # the two routes: a start is reported only to the input it is about (F131). The turn is
        # the *agent's*, built from the oldest eligible entry across its whole queue, so the
        # conversation that starts is frequently not the successor this cutover just created.
        #
        # The diagnostic scenario of "A start is reported only to the input it is about" is the
        # only thing covering `auto_continue`: `cutover_to_successor` returns no auto-continue
        # outcome at all, so this log is the entire record of whether the handover moved.
        started = getattr(result.response, "conversation_id", None)
        if started is not None and started != successor.id:
            # The case that used to be silent. A turn began, so `waiting_reason` is `None` and the
            # branch below was skipped — while the successor did not start and nothing said so.
            logger.info(
                "successor %s did not start immediately: the turn that started carried "
                "conversation %s",
                successor.id,
                started,
            )
        elif result.waiting_reason:
            # Not an error: the queue entry is durable, so the work is not lost — it simply has
            # not started yet, and the operator can start it themselves.
            #
            # What this must not do is claim the *reason* is the successor's. No turn started, but
            # the scheduler still built its attempt from the oldest eligible entry across the
            # agent's whole queue, so the reason it returns frequently describes input from a
            # conversation this cutover never touched. `TurnRefusal.entry_ids` is the one thing
            # that settles it — the same mechanism `agent_trigger.py:1357` uses for the same
            # attribution question — so where it exists and the successor's own entry is not among
            # them, say the refusal was about other input rather than guess.
            refusal = result.refusal
            if refusal is not None and entry.id not in refusal.entry_ids:
                logger.info(
                    "successor %s did not start immediately: the agent refused other input (%s)",
                    successor.id,
                    result.waiting_reason,
                )
            else:
                logger.info(
                    "successor %s did not start immediately: %s",
                    successor.id,
                    result.waiting_reason,
                )

    return successor, entry_id
