"""Shared utilities for the Hub package."""

import uuid
from pathlib import Path
from typing import Any, Dict, Optional

from sqlalchemy.ext.asyncio import AsyncSession


def short_id() -> str:
    """Return an 8-character random hex ID segment."""
    return str(uuid.uuid4())[:8]


async def persist_event(
    session: AsyncSession,
    project_id: str,
    event_type: str,
    data: Optional[Dict[str, Any]] = None,
    agent: Optional[str] = None,
    severity: str = "info",
) -> None:
    """Write one row to event_logs. Import is deferred to avoid circular imports."""
    from .db.models import EventLog

    entry = EventLog(
        id=f"evt-{short_id()}",
        project_id=project_id,
        event_type=event_type,
        agent=agent,
        data=data or {},
        severity=severity,
    )
    session.add(entry)
    await session.commit()


# =============================================================================
# Agent Context File Helpers
# =============================================================================

AGENT_CONTEXT_TEMPLATE = """# {agent_name} Context — AgentWeave

> This file provides essential context for AI coding agents working on this project.

## Agent Identity

**Agent Name**: {agent_name}
**Role**: {role}
**Project**: {project_name}

## Collaboration Context

This project uses **AgentWeave**, a multi-agent AI collaboration framework. You are one of potentially multiple AI agents working together.

### Key Files

- `.agentweave/session.json` — Session configuration and agent assignments
- `.agentweave/protocol.md` — Communication protocol between agents
- `AGENTS.md` — General agent guide for this project
- `CLAUDE.md` — Claude-specific context (if available)
- `GEMINI.md` — Gemini-specific context (if available)

### Workflow

1. Check your inbox for tasks/messages
2. Complete assigned work
3. Update task status
4. Report completion or hand off to next agent

## Guidelines

- Stay focused on assigned tasks
- Communicate clearly with other agents
- Follow the project's coding conventions
- Update documentation when making changes

---
*Generated by AgentWeave Hub*
"""


def get_context_file_for_agent(agent_name: str) -> str:
    """Determine the appropriate context file for an agent."""
    dedicated_contexts = {
        "claude": "CLAUDE.md",
        "gemini": "GEMINI.md",
        "opencode": "OPENCODE.md",
        "kimi": "AGENTS.md",  # Kimi uses generic AGENTS.md
    }
    return dedicated_contexts.get(agent_name.lower(), "AGENTS.md")


def create_agent_context_file(
    agent_name: str,
    role: str = "delegate",
    project_name: str = "Unknown",
) -> str:
    """Create a context file for an agent if it doesn't exist.
    
    Returns the path to the context file.
    """
    import os
    
    context_file = get_context_file_for_agent(agent_name)
    
    # Check multiple possible locations for the file
    possible_dirs = []
    
    # 1. Check Docker-mounted project path first
    project_path = os.environ.get("AGENTWEAVE_PROJECT_PATH")
    if project_path:
        possible_dirs.append(Path(project_path))
    
    # 2. Standard paths
    possible_dirs.extend([
        Path("."),  # Current directory
        Path(".."),  # Parent directory
        Path.home(),  # Home directory
    ])
    
    # Find where to create the file (prefer existing .agentweave location)
    target_dir = None
    for base_dir in possible_dirs:
        agentweave_dir = base_dir / ".agentweave"
        if agentweave_dir.exists():
            target_dir = base_dir
            break
    
    if target_dir is None:
        # Create in current directory
        target_dir = Path(".")
    
    file_path = target_dir / context_file
    
    # Only create if file doesn't exist
    if not file_path.exists():
        content = AGENT_CONTEXT_TEMPLATE.format(
            agent_name=agent_name,
            role=role,
            project_name=project_name,
        )
        try:
            file_path.write_text(content)
            print(f"Created context file: {file_path}")
        except IOError as e:
            print(f"Warning: Could not create context file {file_path}: {e}")
    
    return context_file
